# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 388c54856c44a50fbd484dfa51198bb9106f5f84ee3068fddcc1d74711ecc4c5db544b9aee8ed15b9eefe9ded03519186ce187f6d1119ee6d99ced3b251bc9a7

test:
  secret_key_base: f5321d844c9aac71fbadf237050ed0a531fc756cc6ccf426fff9df18e6e21fad09b10c97e2dac34d413d2e0f0c1212aab0386293c2660c7f4b7dd4976190079a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
